In [10]:
import pandas as pd 
import numpy as np 

df = pd.read_csv('../data/netflix_titles.csv')
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [11]:
# convert the 'date_added' column to datetime format and extract year and month features
df["date_added"] = pd.to_datetime(df["date_added"], errors='coerce')
df["year_added"] = df["date_added"].dt.year.astype('Int64')
df["month_added"] = df["date_added"].dt.month.astype('Int64')

In [12]:
# content age feature
current_year = pd.Timestamp.now().year
df["content_age"] = current_year - df["release_year"]

In [13]:
# primary genre feature
df['primary_genre'] = df['listed_in'].str.split(',').str[0]

In [14]:
df['duration_minutes'] = df['duration'].str.extract('(\d+)')
df['duration_minutes'] = pd.to_numeric(df['duration_minutes'], errors='coerce').astype('Int64')

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
C:\Users\PRASHANT\AppData\Local\Temp\ipykernel_1720\2304914119.py:1: SyntaxWarning: invalid escape sequence '\d'
  df['duration_minutes'] = df['duration'].str.extract('(\d+)')

In [15]:
# region feature
df['primary_country'] = df['country'].str.split(',').str[0]

In [16]:
# binary indicator for movie
df["is_movie"] = np.where(df["type"] == "Movie", 1, 0)

In [17]:
# rename cast to casts to avoid error in postgresql
df.rename(columns={'cast': 'casts'}, inplace=True)

In [18]:
df.to_csv("../data/netflix_featured.csv", index=False)
df.head()

,show_id,type,title,director,casts,country,date_added,release_year,rating,duration,listed_in,description,year_added,month_added,content_age,primary_genre,duration_minutes,primary_country,is_movie
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,2021-09-25,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",2021,9,6,Documentaries,90,United States,1
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",2021,9,5,International TV Shows,2,South Africa,0
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,2021,9,5,Crime TV Shows,1,NaN,0
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,2021-09-24,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",2021,9,5,Docuseries,1,NaN,0
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,2021,9,5,International TV Shows,2,India,0